from . import test_payment_guard
from . import test_schedule_book_more
from . import test_timetable
from . import test_legal_details
from . import test_install_app
from . import test_class_colors
from . import test_studio_controls
from . import test_calendar_grid
from . import test_free_checkout
from . import test_promo_pricing
from . import test_signup_email
from . import test_portal_timezone
from . import test_fixed_class_picker
from . import test_subscription_payment
from . import test_verify_student
from . import test_email_verification
from . import test_desk_sale
from . import test_shop_trial_pending
from . import test_membership_renewal
from . import test_login_destination
from . import test_cash_request
from . import test_cash_paths_matrix
from . import test_blank_email
from . import test_make_student
from . import test_trial_per_discipline
from . import test_cancelled_order_credits
from . import test_make_student_as_manager
from . import test_fixed_slot_warning
from . import test_cash_approval_start_date
from . import test_cash_checkout_http
from . import test_shop_warning_not_for_instructors
from . import test_signup_view_duplicate
from . import test_desk_sale_shows_the_fee

from . import test_nightly_placements_show_on_my_schedule
from . import test_desk_sale_end_to_end
from . import test_notification_bell
from . import test_trial_offer_gate
from . import test_student_list_menu
from . import test_booking_screen_policy
from . import test_notif_key_moments
from . import test_payment_return_states
from . import test_gift
from . import test_signup_duplicate_join
from . import test_duplicate_candidate_list
