from . import test_payment_guard
from . import test_schedule_book_more
from . import test_timetable
from . import test_legal_details
from . import test_install_app
from . import test_class_colors
from . import test_studio_controls
from . import test_calendar_grid
from . import test_free_checkout
from . import test_promo_pricing
from . import test_signup_email
from . import test_portal_timezone
from . import test_fixed_class_picker
from . import test_subscription_payment
from . import test_verify_student
from . import test_email_verification
from . import test_desk_sale
from . import test_shop_trial_pending
from . import test_membership_renewal
from . import test_login_destination
