{
    'name': 'CoreLab Student Portal',
    'version': '19.0.1.24.92',
    'category': 'Services',
    'summary': 'Student-facing CoreLab portal: home, studio, packages, checkout',
    'author': 'Core Lab Studio, S.L.',
    'license': 'LGPL-3',
    'depends': [
        'web',
        'portal',
        'sale',
        'payment',
        'auth_signup',
        'fitness_core',
        'fitness_bookings',
        'fitness_packages',
        'fitness_subscriptions',
        'fitness_notifications',
        # The shop's trial cards link into this module's request form and
        # read fitness.trial.request to know whether one is already open.
        'fitness_trials',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/ir.rule.xml',
        'views/studio_message_views.xml',
        'views/student_profile_simple.xml',
        'views/vip_filters.xml',
        'views/teacher_profile_simple.xml',
        'views/student_profile_views.xml',
        'views/portal_templates.xml',
        'views/portal_shell_override.xml',
        'views/login_override.xml',
        'views/payment_status_override.xml',
        'views/signup_templates.xml',
        'views/signup_consent.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
