from . import fitness_classroom
from . import fitness_class_category
from . import fitness_class_type
from . import fitness_session_type
from . import calendar_event
from . import fitness_class_schedule
from . import fitness_closure_day
from . import fitness_news_post
from . import fitness_dashboard
from . import payment_method
from . import res_users
