from . import test_reassign_wizard
from . import test_bulk_cancel_and_reason
from . import test_class_naming_and_roster
from . import test_manage_classes
from . import test_move_reason_recorded
from . import test_attendance_marking
from . import test_move_clears_the_mark
from . import test_action_overrides_propagate
from . import test_cancel_dialog_opens
from . import test_student_may_cancel_late
from . import test_late_cancel_trial_branch
