{
    'name': 'Fitness Reports – Yoleyva',
    'version': '19.0.2.3.0',
    'category': 'Fitness',
    'summary': 'Manager-only analytics: bookings, revenue, clients, class occupancy (pivot/graph/list)',
    'author': 'Yoleyva Studio',
    'license': 'LGPL-3',
    'depends': [
        'fitness_core',
        'fitness_bookings',
        'fitness_subscriptions',
        'fitness_packages',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/booking_report.xml',
        'views/revenue_report.xml',
        'views/class_report.xml',
        'views/client_report.xml',
        'views/class_summary_report.xml',
        'views/retention_report.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
