from . import ir_http
from . import ir_qweb
from . import res_partner
from . import res_users
from . import sale_order
from . import desk_sale_wizard
from . import studio_message
from . import new_conversation_wizard
from . import calendar_grid
from . import email_verification
from . import fitness_gift
from . import make_student_wizard
from . import res_partner_duplicate
from . import fitness_duplicate_candidate
from . import fitness_duplicate_join_log
